// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQPk8PctGLvJvvMnaxS6x_1f0UCvp5yV8',
    appId: '1:967705491203:web:7952ea46afc91074635b36',
    messagingSenderId: '967705491203',
    projectId: 'unipark-b2324',
    authDomain: 'unipark-b2324.firebaseapp.com',
    storageBucket: 'unipark-b2324.appspot.com',
    measurementId: 'G-QVPMP173WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgvI9jKA4NRsi6_FFEenFapW3ycZd6L8',
    appId: '1:967705491203:android:0e23c62ef038a60e635b36',
    messagingSenderId: '967705491203',
    projectId: 'unipark-b2324',
    storageBucket: 'unipark-b2324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2guyhkiVwnI237IKFHJAFVBQMG0RA_Q',
    appId: '1:967705491203:ios:9e937d64c5e55126635b36',
    messagingSenderId: '967705491203',
    projectId: 'unipark-b2324',
    storageBucket: 'unipark-b2324.appspot.com',
    iosBundleId: 'com.example.applicationDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2guyhkiVwnI237IKFHJAFVBQMG0RA_Q',
    appId: '1:967705491203:ios:9e937d64c5e55126635b36',
    messagingSenderId: '967705491203',
    projectId: 'unipark-b2324',
    storageBucket: 'unipark-b2324.appspot.com',
    iosBundleId: 'com.example.applicationDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQPk8PctGLvJvvMnaxS6x_1f0UCvp5yV8',
    appId: '1:967705491203:web:c7b2887b0799ed4c635b36',
    messagingSenderId: '967705491203',
    projectId: 'unipark-b2324',
    authDomain: 'unipark-b2324.firebaseapp.com',
    storageBucket: 'unipark-b2324.appspot.com',
    measurementId: 'G-P7SP078SR2',
  );
}
